export { Navbar } from './Navbar';
export { Footer } from './Footer';
export { Notificationbar } from './Notificationbar';
export { Signup } from './Signup';
export { Login } from './Login';
export { PrivateRoute } from './PrivateRoute';
export { AnimeComponent } from './AnimeComponent';
export { ListAnime } from './ListAnime';
export { Spinner } from './Spinner';